# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import sqlite3

# Connect to SQLite database (this creates the database if it doesn't exist)
conn = sqlite3.connect("sales_data.db")

# Create a cursor object to execute SQL commands
cursor = conn.cursor()

# Create the 'sales' table with sample columns
cursor.execute('''
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    product TEXT,
    quantity INTEGER,
    price REAL
)
''')

# Insert some sample data into the sales table
cursor.executemany('''
INSERT INTO sales (product, quantity, price)
VALUES (?, ?, ?)
''', [
    ('Product A', 10, 20.0),
    ('Product B', 5, 40.0),
    ('Product C', 8, 15.0),
    ('Product D', 12, 25.0)
])

# Commit changes and close the connection
conn.commit()
conn.close()

import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect("sales_data.db")

# Define the SQL query to get total quantity and revenue per product
query = """
SELECT product,
       SUM(quantity) AS total_qty,
       SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""

# Execute the query and load the results into a pandas DataFrame
df = pd.read_sql_query(query, conn)

# Close the database connection
conn.close()

# Print the DataFrame to show the result
print(df)

import matplotlib.pyplot as plt

# Plot a bar chart for total revenue per product
df.plot(kind='bar', x='product', y='revenue', title='Total Revenue per Product', legend=False)

# Set labels and title for better clarity
plt.xlabel('Product')
plt.ylabel('Revenue')
plt.title('Total Revenue per Product')

# Show the plot
plt.show()

# Optionally, save the chart as a PNG file
plt.savefig("sales_chart.png")